server:
  port: 8090
spring:
  application:
    name: MSS-User-Auth
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: root
  security:
    user:
      name: miracle
      password: Miracle@1
      roles: user
